name: Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .net Onboard
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Change working directory
        working-directory: ./
        run: cd ./
        

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build
